export interface PaTblDocumentoM{
    documento:                 number;
    tipo_Documento?:           number | null;
    serie_Documento:           string;
    empresa?:                  number | null;
    localizacion?:             number | null;
    estacion_Trabajo?:         number | null;
    fecha_Reg?:                number | null;
    fecha_Hora:                Date;
    userName:                  string;
    m_Fecha_Hora?:             Date  | null;
    m_UserName?:               string | null;
    cuenta_Correntista?:       number | null;
    cuenta_Cta:                string;
    id_Documento:              string;
    documento_Nombre:          string;
    documento_NIT:             string;
    documento_Direccion:       string;
    id_Reservacion?:           string | null;
    bodega_Origen?:            number | null;
    bodega_Destino?:           number | null;
    observacion_1?:            string | null;
    fecha_Documento:           Date;
    observacion_2?:            string | null;
    elemento_Asignado?:        number | null;
    estado_Documento:          number;
    impresion_Doc?:            number | null;
    referencia?:               number | null;
    doc_Det?:                  string | null;
    fecha_Ini?:                Date | null;
    fecha_Fin?:                Date | null;
    fecha_Vencimiento?:        Date | null;
    per_O_Cargos?:             boolean | null;
    clasificacion?:            number | null;
    cierre?:                   number | null;
    fecha_Documento_Aux?:      Date | null;
    ref_Serie?:                string | null;
    contabilizado?:            boolean | null;
    turno?:                    number | null;
    observacion_3?:            string | null;
    cuenta_Correntista_Ref?:   number | null;
    cambio?:                   number | null;
    cambio_Moneda?:            number | null;
    bloqueado:                 boolean;
    bloquear_Venta?:           boolean | null;
    razon?:                    number | null;
    proceso?:                  number | null;
    consecutivo_Interno?:      number | null;
    cuenta_Correntista_Ref_2?: number | null;
    localizacion_Ref?:         number | null;
    tipo_Pago?:                number | null;
    campo_1?:                  number | null;
    campo_2?:                  number | null;
    campo_3?:                  number | null;
    fecha_Hora_N?:             number | null;
    fecha_Documento_N?:        number | null;
    seccion?:                  number | null;
    tipo_Actividad?:           number | null;
    cierre_Contable?:          number | null;
    id_Unc?:                   string | null;
    ivA_Exento?:               boolean | null;
    tOpcion?:                  number | null;
    ref_Fecha_Documento?:      Date | null;
    ref_Fecha_Vencimiento?:    Date | null;
    t_Tra_M?:                  number | null; 
    t_Tra_MM?:                 number | null;
    t_Car_Abo_M?:              number | null;
    t_Car_Abo_MM?:             number | null;
    propina_Monto?:            number | null;
    propina_Monto_Moneda?:     number | null;
    ref_Id_Documento?:         string | null;
    t_Tra_M_NImp?:             number | null;
    t_Tra_MM_NImp?:            number | null;
    t_Tra_M_Imp_IVA?:          number | null;
    t_Tra_MM_Imp_IVA?:         number | null;
    t_Tra_M_Imp_ITU?:          number | null;
    t_Tra_MM_Imp_ITU?:         number | null;
    t_Tra_M_Propina?:          number | null;
    t_Tra_MM_Propina?:         number | null;
    t_Tra_M_Cargo?:            number | null;
    t_Tra_MM_Cargo?:           number | null;
    t_Tra_M_Descuento?:        number | null;
    t_Tra_MM_Descuento?:       number | null;
    t_Car_Abo_M_Por_Aplicar?:  number | null;
    t_Car_Abo_MM_Por_Aplicar?: number | null;
    t_Tra_M_Sub?:              number | null;
    t_Tra_MM_Sub?:             number | null;
    vehiculo_Marca?:           number | null;
    vehiculo_Modelo?:          number | null;
    vehiculo_Year?:            number | null;
    vehiculo_Color?:           number | null;
    survey_Record?:            number | null;
    periodo?:                  number | null;
    adults?:                   number | null;
    childrens?:                number | null;
    id_Doc_Alt?:               number | null;
    isR_Retener?:              boolean | null;
    fE_Cae?:                   string | null;
    fE_numeroDocumento?:       string | null;
    fE_numeroDte?:             string | null;
    gpS_Latitud?:              string | null;
    gpS_Longitud?:             string | null;
    consecutivo_Interno_Ref?:  number | null;
    feL_UUID_Anulacion?:       string | null;
    feL_Numero_Acceso?:        number | null;
    fE_Fecha_Certificacion?:   string | null;
    id_Unc_Sync?:              string | null;
    recaptchaToken:            string; 
    isMobile:                  boolean;
}

export interface ParametrosEncabezadoDocumento {
    tAccion:                   number;
    documento:                 number;
    tipo_Documento:            number;
    serie_Documento:           string;
    empresa:                   number;
    localizacion:              number;
    estacion_Trabajo:          number;
    fecha_Reg:                 number;
    fecha_Hora:                Date;
    userName:                  string;
    m_Fecha_Hora?:             Date   | null;
    m_UserName?:               string | null;
    cuenta_Correntista:        number;
    cuenta_Cta:                string;
    id_Documento:              string;
    documento_Nombre:          string;
    documento_NIT:             string;
    documento_Direccion?:      string;
    id_Reservacion?:           string | null;
    bodega_Origen?:            number | null;
    bodega_Destino?:           number | null;
    observacion_1?:            string | null;
    fecha_Documento:           string;
    observacion_2?:            string | null;
    elemento_Asignado?:        number | null;
    estado_Documento:          number;
    impresion_Doc?:            number | null;
    referencia?:               number | null;
    doc_Det?:                  string | null;
    fecha_Ini?:                Date | null;
    fecha_Fin?:                Date | null;
    fecha_Vencimiento?:        Date | null;
    per_O_Cargos?:             boolean | null;
    clasificacion?:            number | null;
    cierre?:                   number | null;
    fecha_Documento_Aux?:      Date | null;
    ref_Serie?:                string | null;
    contabilizado?:            boolean | null;
    turno?:                    number | null;
    observacion_3?:            string | null;
    cuenta_Correntista_Ref?:   number | null;
    cambio?:                   number | null;
    cambio_Moneda?:            number | null;
    bloqueado?:                boolean | null;
    bloquear_Venta?:           boolean | null;
    razon?:                    number | null;
    proceso?:                  number | null;
    consecutivo_Interno?:      number | null;
    cuenta_Correntista_Ref_2?: number | null;
    localizacion_Ref?:         number | null;
    tipo_Pago?:                number | null;
    campo_1?:                  number | null;
    campo_2?:                  number | null;
    campo_3?:                  number | null;
    fecha_Hora_N?:             number | null;
    fecha_Documento_N?:        number | null;
    seccion?:                  number | null;
    tipo_Actividad?:           number | null;
    cierre_Contable?:          number | null;
    id_Unc?:                   string | null;
    ivA_Exento?:               boolean | null;
    tOpcion:                   number;
    ref_Fecha_Documento?:      Date | null;
    ref_Fecha_Vencimiento?:    Date | null;
    t_Tra_M?:                  number | null; 
    t_Tra_MM?:                 number | null;
    t_Car_Abo_M?:              number | null;
    t_Car_Abo_MM?:             number | null;
    propina_Monto?:            number | null;
    propina_Monto_Moneda?:     number | null;
    ref_Id_Documento?:         string | null;
    t_Tra_M_NImp?:             number | null;
    t_Tra_MM_NImp?:            number | null;
    t_Tra_M_Imp_IVA?:          number | null;
    t_Tra_MM_Imp_IVA?:         number | null;
    t_Tra_M_Imp_ITU?:          number | null;
    t_Tra_MM_Imp_ITU?:         number | null;
    t_Tra_M_Propina?:          number | null;
    t_Tra_MM_Propina?:         number | null;
    t_Tra_M_Cargo?:            number | null;
    t_Tra_MM_Cargo?:           number | null;
    t_Tra_M_Descuento?:        number | null;
    t_Tra_MM_Descuento?:       number | null;
    t_Car_Abo_M_Por_Aplicar?:  number | null;
    t_Car_Abo_MM_Por_Aplicar?: number | null;
    t_Tra_M_Sub?:              number | null;
    t_Tra_MM_Sub?:             number | null;
    vehiculo_Marca?:           number | null;
    vehiculo_Modelo?:          number | null;
    vehiculo_Year?:            number | null;
    vehiculo_Color?:           number | null;
    survey_Record?:            number | null;
    periodo?:                  number | null;
    adults?:                   number | null;
    childrens?:                number | null;
    id_Doc_Alt?:               number | null;
    isR_Retener?:              boolean | null;
    fE_Cae?:                   string | null;
    fE_numeroDocumento?:       string | null;
    fE_numeroDte?:             string | null;
    gpS_Latitud?:              string | null;
    gpS_Longitud?:             string | null;
    consecutivo_Interno_Ref?:  number | null;
    feL_UUID_Anulacion?:       string | null;
    feL_Numero_Acceso?:        number | null;
    fE_Fecha_Certificacion?:   string | null;
    id_Unc_Sync?:              string | null;
    recaptchaToken:            string; 
    isMobile:                  boolean;
}
