namespace CuentasxCobrar.Model
{
    public class PaTblDocumentoM
    {
        public int TAccion { get; set; }
        public int Documento { get; set; }
        public int Tipo_Documento { get; set; }
        public String Serie_Documento { get; set; }
        public int Empresa { get; set; }
        public int Localizacion { get; set; }
        public int Estacion_Trabajo { get; set; }
        public int Fecha_Reg { get; set; }
        public DateTime Fecha_Hora { get; set; }
        public String UserName { get; set; }
        public DateTime? M_Fecha_Hora { get; set; }
        public String? M_UserName { get; set; }
        public int Cuenta_Correntista { get; set; }
        public String Cuenta_Cta { get; set; }
        public String Id_Documento { get; set; }
        public String Documento_Nombre { get; set; }
        public String Documento_NIT { get; set; }
        public String Documento_Direccion { get; set; }
        public String? Id_Reservacion { get; set; }
        public int? Bodega_Origen { get; set; }
        public int? Bodega_Destino { get; set; }
        public String? Observacion_1 { get; set; }
        public DateTime Fecha_Documento { get; set; }
        public String? Observacion_2 { get; set; }
        public int? Elemento_Asignado { get; set; }
        public int Estado_Documento { get; set; }
        public int? Impresion_Doc { get; set; }
        public int? Referencia { get; set; }
        public String? Doc_Det { get; set; }
        public DateTime? Fecha_Ini { get; set; }
        public DateTime? Fecha_Fin { get; set; }
        public DateTime? Fecha_Vencimiento { get; set; }
        public bool? Per_O_Cargos { get; set; }
        public int? Clasificacion { get; set; }
        public int? Cierre { get; set; }
        public DateTime? Fecha_Documento_Aux { get; set; }
        public String? Ref_Serie { get; set; }
        public bool? Contabilizado { get; set; }
        public int? Turno { get; set; }
        public String? Observacion_3 { get; set; }
        public int? Cuenta_Correntista_Ref { get; set; }
        public decimal? Cambio { get; set; }
        public decimal? Cambio_Moneda { get; set; }
        public bool? Bloqueado { get; set; }
        public bool? Bloquear_Venta { get; set; }
        public int? Razon { get; set; }
        public int? Proceso { get; set; }
        public int? Consecutivo_Interno { get; set; }
        public int? Cuenta_Correntista_Ref_2 { get; set; }
        public int? Localizacion_Ref { get; set; }
        public int? Tipo_Pago { get; set; }
        public decimal? Campo_1 { get; set; }
        public decimal? Campo_2 { get; set; }
        public decimal? Campo_3 { get; set; }
        public int? Fecha_Hora_N { get; set; }
        public int? Fecha_Documento_N { get; set; }
        public int? Seccion { get; set; }
        public int? Tipo_Actividad { get; set; }
        public int? Cierre_Contable { get; set; }
        public Guid? Id_Unc { get; set; }
        public bool? IVA_Exento { get; set; }
        public int TOpcion { get; set; }
        public DateTime? Ref_Fecha_Documento { get; set; }
        public DateTime? Ref_Fecha_Vencimiento { get; set; }
        public decimal? T_Tra_M { get; set; }
        public decimal? T_Tra_MM { get; set; }
        public decimal? T_Car_Abo_M { get; set; }
        public decimal? T_Car_Abo_MM { get; set; }
        public decimal? Propina_Monto { get; set; }
        public decimal? Propina_Monto_Moneda { get; set; }
        public String? Ref_Id_Documento { get; set; }
        public decimal? T_Tra_M_NImp { get; set; }
        public decimal? T_Tra_MM_NImp { get; set; }
        public decimal? T_Tra_M_Imp_IVA { get; set; }
        public decimal? T_Tra_MM_Imp_IVA { get; set; }
        public decimal? T_Tra_M_Imp_ITU { get; set; }
        public decimal? T_Tra_MM_Imp_ITU { get; set; }
        public decimal? T_Tra_M_Propina { get; set; }
        public decimal? T_Tra_MM_Propina { get; set; }
        public decimal? T_Tra_M_Cargo { get; set; }
        public decimal? T_Tra_MM_Cargo { get; set; }
        public decimal? T_Tra_M_Descuento { get; set; }
        public decimal? T_Tra_MM_Descuento { get; set; }
        public decimal? T_Car_Abo_M_Por_Aplicar { get; set; }
        public decimal? T_Car_Abo_MM_Por_Aplicar { get; set; }
        public decimal? T_Tra_M_Sub { get; set; }
        public decimal? T_Tra_MM_Sub { get; set; }
        public int? Vehiculo_Marca { get; set; }
        public int? Vehiculo_Modelo { get; set; }
        public int? Vehiculo_Year { get; set; }
        public int? Vehiculo_Color { get; set; }
        public int? Survey_Record { get; set; }
        public int? Periodo { get; set; }
        public int? Adults { get; set; }
        public int? Childrens { get; set; }
        public int? Id_Doc_Alt { get; set; }
        public bool? ISR_Retener { get; set; }
        public String? FE_Cae { get; set; }
        public String? FE_numeroDocumento { get; set; }
        public String? FE_numeroDte { get; set; }
        public String? GPS_Latitud { get; set; }
        public String? GPS_Longitud { get; set; }
        public int? Consecutivo_Interno_Ref { get; set; }
        public String? FEL_UUID_Anulacion { get; set; }
        public int? FEL_Numero_Acceso { get; set; }
        public String? FE_Fecha_Certificacion { get; set; }
        public Guid? Id_Unc_Sync { get; set; }
        public String RecaptchaToken { get; set; }
        public bool IsMobile { get; set; }

    }
}
