name: test_cuenta_corriente
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  jwt_decoder: ^2.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.11
  table_calendar: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  animated_background: ^2.0.0
  country_icons: ^2.0.2
  dio: ^4.0.6
  flutter_spinkit: ^5.2.1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  collection: ^1.18.0
  flutter_localizations: 
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  awesome_dialog: ^3.2.0
  flutter_initicon: ^3.0.1
  custom_refresh_indicator: ^4.0.1
  g_recaptcha_v3: ^0.0.6
  number2words: ^0.0.5
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^5.0.0
  printing: ^5.13.2
 

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  intl_translation: ^0.20.0
  intl_utils: ^2.0.0
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Fondos/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
